services:
  master:
    build:
      context: .
      dockerfile: Dockerfile.master
    container_name: ansible-master
    hostname: master
    networks:
      ansible-lab:
        ipv4_address: 172.25.0.10
    volumes:
      - ./ansible:/root/ansible

  mysqldb:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    container_name: ansible-mysqldb
    hostname: mysqldb
    networks:
      ansible-lab:
        ipv4_address: 172.25.0.11

  host1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ansible-host1
    hostname: host1
    networks:
      ansible-lab:
        ipv4_address: 172.25.0.12

  host2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ansible-host2
    hostname: host2
    networks:
      ansible-lab:
        ipv4_address: 172.25.0.13

  host3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ansible-host3
    hostname: host3
    networks:
      ansible-lab:
        ipv4_address: 172.25.0.14

networks:
  ansible-lab:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/24
